# Generated by Django 5.1.6 on 2025-03-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='namemodel',
            field=models.CharField(max_length=55),
        ),
    ]
