# Generated by Django 5.1.6 on 2025-03-05 03:33

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_namemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonemodel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='NP', unique=True),
        ),
    ]
